title: BioFu
repository: telatin/biofu
lang: en
description: Command line utilities for bioinformaticians

readme_index:
  with_frontmatter: true

theme: null

remote_theme: rundocs/jekyll-rtd-theme

plugins:
  - jekyll-remote-theme

markdown: CommonMarkGhPages
commonmark:
  options: ['SMART']
  extensions: ['table']
